name: CI
on: push  

jobs:
  Practice_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: npm dependecies
      run: npm ci
    - name: lint runner    
      run: npm run lint
    #- name: test runner
    #  run: npm test
    - name: build runner
      run: npm run build
    - name: deploy runner
      run: npm run deploy  
  